export const MSG_ADD_TO_CARD_SUCCESS = 'Mua Hàng Thành Công !'
export const MSG_UPDATE_TO_CARD_SUCCESS = 'Đã Cập Nhật Số Lượng'
export const MSG_ADD_CARD_SUCCESS = ' Vào Giỏ Hàng Thành Công !'
export const MSG_DELETE_TO_CARD_SUCCESS = ' Thành Công Khỏi Giỏ Hàng !'
export const EMPTY = 'Chưa Có Sản Phẩm Nào Trong Giỏ Hàng !'
export const MSG_WELLCOM = 'Wellcom To My Web !'